28-Jun-21 00:46:47 - WARNING - Not Found: /favicon.ico
28-Jun-21 00:48:06 - INFO - usuario resgitrado:coco2
28-Jun-21 00:52:58 - INFO - usuario resgitrado:kevinrkoyes
28-Jun-21 01:11:51 - WARNING - Not Found: /favicon.ico
28-Jun-21 01:20:28 - INFO - usuario logueado:elVictor099
28-Jun-21 01:45:29 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 01:45:31 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 01:45:40 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/templates/compartir.html changed, reloading.
28-Jun-21 01:53:00 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 01:54:42 - WARNING - Not Found: /favicon.ico
28-Jun-21 01:58:11 - INFO - usuario logueado:elVictor099
28-Jun-21 02:00:15 - WARNING - Not Found: /favicon.ico
28-Jun-21 02:03:47 - INFO - usuario logueado:elVictor099
28-Jun-21 02:04:37 - ERROR - Internal Server Error: /compartir
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/decoradores.py", line 15, in interna
    return vista(request, *args, **kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/views.py", line 443, in compartir
    if existen_datos:
NameError: name 'existen_datos' is not defined
28-Jun-21 02:08:55 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:09:24 - ERROR - Internal Server Error: /compartir
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/decoradores.py", line 15, in interna
    return vista(request, *args, **kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/views.py", line 444, in compartir
    llave_enviada = enviar_llave_publica(token, chat_id)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/views.py", line 424, in enviar_llave_publica
    nick = request.session.get('usuario', 'anonimo')
NameError: name 'request' is not defined
28-Jun-21 02:11:02 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:28:51 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/templates/compartir.html changed, reloading.
28-Jun-21 02:29:56 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:36:29 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:36:54 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/templates/compartir.html changed, reloading.
28-Jun-21 02:37:11 - WARNING - Not Found: /favicon.ico
28-Jun-21 02:40:41 - INFO - usuario logueado:elVictor099
28-Jun-21 02:41:15 - ERROR - Internal Server Error: /compartir
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/decoradores.py", line 15, in interna
    return vista(request, *args, **kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/views.py", line 445, in compartir
    llave_enviada = enviar_llave_publica(token, chat_id, datos_almacenados, password)
NameError: name 'password' is not defined
28-Jun-21 02:41:40 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:42:01 - ERROR - Internal Server Error: /compartir
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/decoradores.py", line 15, in interna
    return vista(request, *args, **kwargs)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/views.py", line 445, in compartir
    llave_enviada = enviar_llave_publica(token, chat_id, datos_almacenados)
  File "/home/pruebas/modificado/GestionClaves/GestionClaves/views.py", line 428, in enviar_llave_publica
    mensaje_enviado = 'https://api.telegram.org/bot' + token + '/sendMessage?chat_id=' + chat_id + '&parse_mode=Markdown&text=' + llave_publica
TypeError: can only concatenate str (not "bytes") to str
28-Jun-21 02:42:59 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:48:08 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:50:34 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 02:52:39 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/templates/barra2.html changed, reloading.
28-Jun-21 02:54:27 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/templates/llave.html changed, reloading.
28-Jun-21 02:56:49 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:07:54 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:18:46 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:19:51 - WARNING - Not Found: /favicon.ico
28-Jun-21 03:23:18 - INFO - usuario logueado:elVictor099
28-Jun-21 03:38:42 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:49:33 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:50:53 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:51:35 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 03:52:18 - WARNING - Not Found: /favicon.ico
28-Jun-21 03:55:54 - INFO - usuario logueado:elVictor099
28-Jun-21 04:06:15 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 04:13:01 - WARNING - Not Found: /favicon.ico
28-Jun-21 04:16:28 - INFO - usuario logueado:elVictor099
28-Jun-21 13:27:46 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 13:30:38 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 13:47:47 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 13:48:24 - WARNING - Not Found: /favicon.ico
28-Jun-21 13:50:57 - INFO - usuario resgitrado:kevinrkoyes
28-Jun-21 13:58:22 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 14:01:19 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 14:05:17 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 14:11:14 - INFO - usuario logueado:elVictor099
28-Jun-21 14:58:19 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 14:58:38 - WARNING - Not Found: /favicon.ico
28-Jun-21 15:02:07 - INFO - usuario logueado:elVictor099
28-Jun-21 15:02:35 - INFO - el usuario:Victor Hdez Yovalregistro las credenciales de la cuentaGoogle
28-Jun-21 15:30:59 - INFO - /home/pruebas/modificado/GestionClaves/GestionClaves/views.py changed, reloading.
28-Jun-21 15:31:33 - WARNING - Not Found: /favicon.ico
28-Jun-21 15:35:05 - INFO - usuario logueado:elVictor099
28-Jun-21 15:42:26 - WARNING - Not Found: /favicon.ico
